### ISSUE TITLE
devcontainer setup

### ISSUE THREAD

**Issue by EdwardIrby** [plaited/plaited#19]
To run playwirght test for visual regression we are going to need docker. Further to run the test and workshop that use two different JS runtimes we should probably orchestrate that with a docker-compose.yml. Since we provide templates already for recommended vscode settings and workshop is dependent on the vscode extension for playwright to visually navigate between stories in the browser we should also provide templates for devcontainers.

See https://code.visualstudio.com/docs/devcontainers/containers

**Comment by alisonailea** [comment]
Resources:
https://hub.docker.com/r/denoland/deno
https://playwright.dev/docs/docker

**Comment by EdwardIrby** [comment]
No dev container for this repo. Instead I created a docker container to run test that needed to be executed in the browser context. This should server as a starter example for creating a devcontainer for the app we're making.
